HOMEPAGE = "https://ollama.com/library/qwen3"
SUMMARY = "Qwen3 is the latest generation of large language models in Qwen series,\
offering a comprehensive suite of dense and mixture-of-experts (MoE) models."
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://sha256-${LICESE_SHA256};md5=6775653e10231aa75a3b7ebc7bae831f"
BPN = "qwen3"

LICESE_SHA256 = "d18a5cc71b84bc4af394a31116bd3932b42241de70c77d2b76d69a314ec8aa12"
PARAMS_SHA256 = "cff3f395ef3756ab63e58b0ad1b32bb6f802905cae1472e6a12034e4246fbbdb"

inherit ollama-model

