# [golang.org/x/sys v0.37.0] git ls-remote https://go.googlesource.com/sys 1edeebeea09c66c5a886ccfefb1be5dafac5c893
SRCREV_sys = "1edeebeea09c66c5a886ccfefb1be5dafac5c893"
SRC_URI += "git://go.googlesource.com/sys;name=sys;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/golang.org/x/sys"

# [golang.org/x/mod v0.30.0] git ls-remote https://go.googlesource.com/mod 7416265ac6eca137286fb2adcc87f9feec458b4c
SRCREV_mod = "7416265ac6eca137286fb2adcc87f9feec458b4c"
SRC_URI += "git://go.googlesource.com/mod;name=mod;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/golang.org/x/mod"

# [golang.org/x/exp v0.0.0-20250218142911-aa4b98e5adaa] git ls-remote https://go.googlesource.com/exp aa4b98e5adaa776b18e544db3ee2b32a74335849
SRCREV_exp = "aa4b98e5adaa776b18e544db3ee2b32a74335849"
SRC_URI += "git://go.googlesource.com/exp;name=exp;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/golang.org/x/exp"

# [golang.org/x/net v0.46.0] git ls-remote https://go.googlesource.com/net 2002a064a49010d8b881673c73f04e0b741e7c32
SRCREV_net = "2002a064a49010d8b881673c73f04e0b741e7c32"
SRC_URI += "git://go.googlesource.com/net;name=net;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/golang.org/x/net"

# [gopkg.in/yaml.v3 v3.0.1] git ls-remote https://github.com/go-yaml/yaml f6f7691b1fdeb513f56608cd2c32c51f8194bf51
SRCREV_yaml.v3 = "f6f7691b1fdeb513f56608cd2c32c51f8194bf51"
SRC_URI += "git://github.com/go-yaml/yaml;name=yaml.v3;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/gopkg.in/yaml.v3"

# [golang.org/x/sync v0.17.0] git ls-remote https://go.googlesource.com/sync 04914c200cb38d4ea960ee6a4c314a028c632991
SRCREV_sync = "04914c200cb38d4ea960ee6a4c314a028c632991"
SRC_URI += "git://go.googlesource.com/sync;name=sync;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/golang.org/x/sync"

# [golang.org/x/arch v0.8.0] git ls-remote https://go.googlesource.com/arch 5d0b1102bee052ce00bf47f9cfef8f73d2ac6d46
SRCREV_arch = "5d0b1102bee052ce00bf47f9cfef8f73d2ac6d46"
SRC_URI += "git://go.googlesource.com/arch;name=arch;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/golang.org/x/arch"

# [golang.org/x/term v0.36.0] git ls-remote https://go.googlesource.com/term 3a0828a6667fd19fb680702513ff01f7afe76772
SRCREV_term = "3a0828a6667fd19fb680702513ff01f7afe76772"
SRC_URI += "git://go.googlesource.com/term;name=term;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/golang.org/x/term"

# [golang.org/x/text v0.30.0] git ls-remote https://go.googlesource.com/text c6abd0305e90ada9293824462268d0ec20d02e5e
SRCREV_x-text = "c6abd0305e90ada9293824462268d0ec20d02e5e"
SRC_URI += "git://go.googlesource.com/text;name=x-text;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/golang.org/x/text"

# [golang.org/x/image v0.22.0] git ls-remote https://go.googlesource.com/image 3724ab8af5c31f982e13765ba3707ffe5c463e64
SRCREV_image = "3724ab8af5c31f982e13765ba3707ffe5c463e64"
SRC_URI += "git://go.googlesource.com/image;name=image;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/golang.org/x/image"

# [golang.org/x/tools v0.38.0] git ls-remote https://go.googlesource.com/tools a22b5e8a9b8d2234e1e960ec2473e4011f012a6b
SRCREV_tools = "a22b5e8a9b8d2234e1e960ec2473e4011f012a6b"
SRC_URI += "git://go.googlesource.com/tools;name=tools;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/golang.org/x/tools"

# [gonum.org/v1/gonum v0.15.0] git ls-remote https://github.com/gonum/gonum c72bc440ad773810d5787c662f2b67a5e0ded3e4
SRCREV_gonum = "c72bc440ad773810d5787c662f2b67a5e0ded3e4"
SRC_URI += "git://github.com/gonum/gonum;name=gonum;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/gonum.org/v1/gonum"

# [github.com/kr/text v0.2.0] git ls-remote https://github.com/kr/text 702c74938df48b97370179f33ce2107bd7ff3b3e
SRCREV_text = "702c74938df48b97370179f33ce2107bd7ff3b3e"
SRC_URI += "git://github.com/kr/text;name=text;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/kr/text"

# [github.com/xtgo/set v1.0.0] git ls-remote https://github.com/xtgo/set 708d80f4a27458f99f8ca12bd0e638c6ee65627f
SRCREV_set = "708d80f4a27458f99f8ca12bd0e638c6ee65627f"
SRC_URI += "git://github.com/xtgo/set;name=set;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/xtgo/set"

# [gorgonia.org/vecf32 v0.9.0] git ls-remote https://github.com/gorgonia/vecf32 50ea049a9000a9d51e09929ee39572ff2ba68b59
SRCREV_vecf32 = "50ea049a9000a9d51e09929ee39572ff2ba68b59"
SRC_URI += "git://github.com/gorgonia/vecf32;name=vecf32;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/gorgonia.org/vecf32"

# [gorgonia.org/vecf64 v0.9.0] git ls-remote https://github.com/gorgonia/vecf64 1a1e7411aed011ba757953c004380fa32cce0293
SRCREV_vecf64 = "1a1e7411aed011ba757953c004380fa32cce0293"
SRC_URI += "git://github.com/gorgonia/vecf64;name=vecf64;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/gorgonia.org/vecf64"

# [golang.org/x/crypto v0.43.0] git ls-remote https://go.googlesource.com/crypto 627cb894b6b2021e34c4ad4af4c0a963127491e4
SRCREV_crypto = "627cb894b6b2021e34c4ad4af4c0a963127491e4"
SRC_URI += "git://go.googlesource.com/crypto;name=crypto;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/golang.org/x/crypto"

# [github.com/chewxy/hm v1.0.0] git ls-remote https://github.com/chewxy/hm 61efb3290a086d1335e8954b3734c102126818ba
SRCREV_hm = "61efb3290a086d1335e8954b3734c102126818ba"
SRC_URI += "git://github.com/chewxy/hm;name=hm;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/chewxy/hm"

# [golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1] git ls-remote https://go.googlesource.com/xerrors 5ec99f83aff198f5fbd629d6c8d8eb38a04218ca
SRCREV_xerrors = "5ec99f83aff198f5fbd629d6c8d8eb38a04218ca"
SRC_URI += "git://go.googlesource.com/xerrors;name=xerrors;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/golang.org/x/xerrors"

# [github.com/pkg/errors v0.9.1] git ls-remote https://github.com/pkg/errors 614d223910a179a466c1767a985424175c39b465
SRCREV_errors = "614d223910a179a466c1767a985424175c39b465"
SRC_URI += "git://github.com/pkg/errors;name=errors;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/pkg/errors"

# [github.com/google/uuid v1.6.0] git ls-remote https://github.com/google/uuid 0f11ee6918f41a04c201eceeadf612a377bc7fbc
SRCREV_uuid = "0f11ee6918f41a04c201eceeadf612a377bc7fbc"
SRC_URI += "git://github.com/google/uuid;name=uuid;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/google/uuid"

# [github.com/spf13/cobra v1.7.0] git ls-remote https://github.com/spf13/cobra 4dd4b25de38418174a6e859e8a32eaccca32dccc
SRCREV_cobra = "4dd4b25de38418174a6e859e8a32eaccca32dccc"
SRC_URI += "git://github.com/spf13/cobra;name=cobra;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/spf13/cobra"

# [github.com/rivo/uniseg v0.2.0] git ls-remote https://github.com/rivo/uniseg 75711fccf6a3e85bc74c241e2dddd06a9bc9e53d
SRCREV_uniseg = "75711fccf6a3e85bc74c241e2dddd06a9bc9e53d"
SRC_URI += "git://github.com/rivo/uniseg;name=uniseg;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/rivo/uniseg"

# [github.com/spf13/pflag v1.0.5] git ls-remote https://github.com/spf13/pflag 2e9d26c8c37aae03e3f9d4e90b7116f5accb7cab
SRCREV_pflag = "2e9d26c8c37aae03e3f9d4e90b7116f5accb7cab"
SRC_URI += "git://github.com/spf13/pflag;name=pflag;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/spf13/pflag"

# [github.com/x448/float16 v0.8.4] git ls-remote https://github.com/x448/float16 cb9afec31f2649663ebb64da5c6c32c3d365c3ca
SRCREV_float16 = "cb9afec31f2649663ebb64da5c6c32c3d365c3ca"
SRC_URI += "git://github.com/x448/float16;name=float16;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/x448/float16"

# [github.com/gin-gonic/gin v1.10.0] git ls-remote https://github.com/gin-gonic/gin 75ccf94d605a05fe24817fc2f166f6f2959d5cea
SRCREV_gin = "75ccf94d605a05fe24817fc2f166f6f2959d5cea"
SRC_URI += "git://github.com/gin-gonic/gin;name=gin;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/gin-gonic/gin"

# [github.com/google/go-cmp v0.7.0] git ls-remote https://github.com/google/go-cmp 9b12f366a942ebc7254abc7f32ca05068b455fb7
SRCREV_go-cmp = "9b12f366a942ebc7254abc7f32ca05068b455fb7"
SRC_URI += "git://github.com/google/go-cmp;name=go-cmp;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/google/go-cmp"

# [github.com/chewxy/math32 v1.11.0] git ls-remote https://github.com/chewxy/math32 7caa3bba2ee1e00c12d7a319f964dc7dcb4adc03
SRCREV_math32 = "7caa3bba2ee1e00c12d7a319f964dc7dcb4adc03"
SRC_URI += "git://github.com/chewxy/math32;name=math32;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/chewxy/math32"

# [github.com/gogo/protobuf v1.3.2] git ls-remote https://github.com/gogo/protobuf b03c65ea87cdc3521ede29f62fe3ce239267c1bc
SRCREV_gogo-protobuf = "b03c65ea87cdc3521ede29f62fe3ce239267c1bc"
SRC_URI += "git://github.com/gogo/protobuf;name=gogo-protobuf;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/gogo/protobuf"

# [github.com/goccy/go-json v0.10.2] git ls-remote https://github.com/goccy/go-json 8e8cdeacf2f2faef082f32848138f0f9af7cfb66
SRCREV_go-json = "8e8cdeacf2f2faef082f32848138f0f9af7cfb66"
SRC_URI += "git://github.com/goccy/go-json;name=go-json;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/goccy/go-json"

# [github.com/ledongthuc/pdf v0.0.0-20250511090121-5959a4027728] git ls-remote https://github.com/ledongthuc/pdf 5959a40277285327ee480a3bfd8ec9289fc1ab50
SRCREV_pdf = "5959a40277285327ee480a3bfd8ec9289fc1ab50"
SRC_URI += "git://github.com/ledongthuc/pdf;name=pdf;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/ledongthuc/pdf"

# [github.com/pdevine/tensor v0.0.0-20240510204454-f88f4562727c] git ls-remote https://github.com/pdevine/tensor f88f4562727c20425d4b6cad576a4401aa4caa63
SRCREV_tensor = "f88f4562727c20425d4b6cad576a4401aa4caa63"
SRC_URI += "git://github.com/pdevine/tensor;name=tensor;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/pdevine/tensor"

# [github.com/cloudwego/iasm v0.2.0] git ls-remote https://github.com/cloudwego/iasm db7298c17e362736a9954240db007c2432bf1fa1
SRCREV_iasm = "db7298c17e362736a9954240db007c2432bf1fa1"
SRC_URI += "git://github.com/cloudwego/iasm;name=iasm;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/cloudwego/iasm"

# [github.com/leodido/go-urn v1.4.0] git ls-remote https://github.com/leodido/go-urn d725923fe33ce69c89b9e2033d069099b498224f
SRCREV_go-urn = "d725923fe33ce69c89b9e2033d069099b498224f"
SRC_URI += "git://github.com/leodido/go-urn;name=go-urn;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/leodido/go-urn"

# [github.com/golang/protobuf v1.5.4] git ls-remote https://github.com/golang/protobuf 75de7c059e36b64f01d0dd234ff2fff404ec3374
SRCREV_protobuf = "75de7c059e36b64f01d0dd234ff2fff404ec3374"
SRC_URI += "git://github.com/golang/protobuf;name=protobuf;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/golang/protobuf"

# [github.com/dlclark/regexp2 v1.11.4] git ls-remote https://github.com/dlclark/regexp2 5f3687ab77460347a912d278c2e13844542834fd
SRCREV_regexp2 = "5f3687ab77460347a912d278c2e13844542834fd"
SRC_URI += "git://github.com/dlclark/regexp2;name=regexp2;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/dlclark/regexp2"

# [github.com/davecgh/go-spew v1.1.1] git ls-remote https://github.com/davecgh/go-spew 8991bc29aa16c548c550c7ff78260e27b9ab7c73
SRCREV_go-spew = "8991bc29aa16c548c550c7ff78260e27b9ab7c73"
SRC_URI += "git://github.com/davecgh/go-spew;name=go-spew;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/davecgh/go-spew"

# [github.com/mailru/easyjson v0.7.7] git ls-remote https://github.com/mailru/easyjson c120ca7ced6051261161ce15e8f1542a4b2567fc
SRCREV_easyjson = "c120ca7ced6051261161ce15e8f1542a4b2567fc"
SRC_URI += "git://github.com/mailru/easyjson;name=easyjson;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/mailru/easyjson"

# [github.com/bytedance/sonic v1.11.6] git ls-remote https://github.com/bytedance/sonic 2b66aefcd60d189cff2669213f682557216b686f
SRCREV_sonic = "2b66aefcd60d189cff2669213f682557216b686f"
SRC_URI += "git://github.com/bytedance/sonic;name=sonic;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/bytedance/sonic"

# [github.com/gin-contrib/sse v0.1.0] git ls-remote https://github.com/gin-contrib/sse 54d8467d122d380a14768b6b4e5cd7ca4755938f
SRCREV_sse = "54d8467d122d380a14768b6b4e5cd7ca4755938f"
SRC_URI += "git://github.com/gin-contrib/sse;name=sse;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/gin-contrib/sse"

# [github.com/mattn/go-isatty v0.0.20] git ls-remote https://github.com/mattn/go-isatty a7c02353c47bc4ec6b30dc9628154ae4fe760c11
SRCREV_go-isatty = "a7c02353c47bc4ec6b30dc9628154ae4fe760c11"
SRC_URI += "git://github.com/mattn/go-isatty;name=go-isatty;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/mattn/go-isatty"

# [github.com/ugorji/go/codec v1.2.12] git ls-remote https://github.com/ugorji/go 43b79bfcab412eeb73e92181a2190e97a5520566
SRCREV_codec = "43b79bfcab412eeb73e92181a2190e97a5520566"
SRC_URI += "git://github.com/ugorji/go;name=codec;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/ugorji/go/codec"

# [google.golang.org/protobuf v1.34.1] git ls-remote https://github.com/protocolbuffers/protobuf-go 4a76e11653e368b9331815e1eb98e0cedc28997f
SRCREV_google.golang.org-protobuf = "4a76e11653e368b9331815e1eb98e0cedc28997f"
SRC_URI += "git://github.com/protocolbuffers/protobuf-go;name=google.golang.org-protobuf;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/google.golang.org/protobuf"

# [github.com/TheTitanrain/w32 v0.0.0-20180517000239-4f5cfb03fabf] git ls-remote https://github.com/TheTitanrain/w32 4f5cfb03fabf8c92e8de36012c944d10a5a49b19
SRCREV_w32 = "4f5cfb03fabf8c92e8de36012c944d10a5a49b19"
SRC_URI += "git://github.com/TheTitanrain/w32;name=w32;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/TheTitanrain/w32"

# [github.com/mattn/go-sqlite3 v1.14.24] git ls-remote https://github.com/mattn/go-sqlite3 846fea6c1443e8cc366fc1966fe078d7f825f6a9
SRCREV_go-sqlite3 = "846fea6c1443e8cc366fc1966fe078d7f825f6a9"
SRC_URI += "git://github.com/mattn/go-sqlite3;name=go-sqlite3;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/mattn/go-sqlite3"

# [github.com/stretchr/testify v1.9.0] git ls-remote https://github.com/stretchr/testify bb548d0473d4e1c9b7bbfd6602c7bf12f7a84dd2
SRCREV_testify = "bb548d0473d4e1c9b7bbfd6602c7bf12f7a84dd2"
SRC_URI += "git://github.com/stretchr/testify;name=testify;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/stretchr/testify"

# [github.com/buger/jsonparser v1.1.1] git ls-remote https://github.com/buger/jsonparser df3ea76ece10095374fd1c9a22a4fb85a44efc42
SRCREV_jsonparser = "df3ea76ece10095374fd1c9a22a4fb85a44efc42"
SRC_URI += "git://github.com/buger/jsonparser;name=jsonparser;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/buger/jsonparser"

# [github.com/gin-contrib/cors v1.7.2] git ls-remote https://github.com/gin-contrib/cors 064064f7214ebfe75a019e6534b92f1ce709065e
SRCREV_cors = "064064f7214ebfe75a019e6534b92f1ce709065e"
SRC_URI += "git://github.com/gin-contrib/cors;name=cors;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/gin-contrib/cors"

# [github.com/json-iterator/go v1.1.12] git ls-remote https://github.com/json-iterator/go 024077e996b048517130b21ea6bf12aa23055d3d
SRCREV_go = "024077e996b048517130b21ea6bf12aa23055d3d"
SRC_URI += "git://github.com/json-iterator/go;name=go;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/json-iterator/go"

# [github.com/d4l3k/go-bfloat16 v0.0.0-20211005043715-690c3bdd05f1] git ls-remote https://github.com/d4l3k/go-bfloat16 690c3bdd05f13e639d272b6b05061ea57e639d2d
SRCREV_go-bfloat16 = "690c3bdd05f13e639d272b6b05061ea57e639d2d"
SRC_URI += "git://github.com/d4l3k/go-bfloat16;name=go-bfloat16;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/d4l3k/go-bfloat16"

# [github.com/emirpasic/gods/v2 v2.0.0-alpha] git ls-remote https://github.com/emirpasic/gods 14f714261f50e6d3e4af1cd29e4ae11ffdedab94
SRCREV_v2 = "14f714261f50e6d3e4af1cd29e4ae11ffdedab94"
SRC_URI += "git://github.com/emirpasic/gods;name=v2;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/emirpasic/gods/v2"

# [github.com/cloudwego/base64x v0.1.4] git ls-remote https://github.com/cloudwego/base64x aa02bf235e2a286ef3a99bacefb460195fc5a16b
SRCREV_base64x = "aa02bf235e2a286ef3a99bacefb460195fc5a16b"
SRC_URI += "git://github.com/cloudwego/base64x;name=base64x;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/cloudwego/base64x"

# [github.com/containerd/console v1.0.3] git ls-remote https://github.com/containerd/console b5cb846c9186d67bcae3ce3c324e47cd317d9527
SRCREV_console = "b5cb846c9186d67bcae3ce3c324e47cd317d9527"
SRC_URI += "git://github.com/containerd/console;name=console;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/containerd/console"

# [github.com/mattn/go-runewidth v0.0.14] git ls-remote https://github.com/mattn/go-runewidth 2c6a438f68cfe01255a90824599da41fdf76d1e2
SRCREV_go-runewidth = "2c6a438f68cfe01255a90824599da41fdf76d1e2"
SRC_URI += "git://github.com/mattn/go-runewidth;name=go-runewidth;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/mattn/go-runewidth"

# [github.com/google/flatbuffers v24.3.25+incompatible] git ls-remote https://github.com/google/flatbuffers 595bf0007ab1929570c7671f091313c8fc20644e
SRCREV_flatbuffers = "595bf0007ab1929570c7671f091313c8fc20644e"
SRC_URI += "git://github.com/google/flatbuffers;name=flatbuffers;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/google/flatbuffers"

# [github.com/pmezard/go-difflib v1.0.0] git ls-remote https://github.com/pmezard/go-difflib 792786c7400a136282c1664665ae0a8db921c6c2
SRCREV_go-difflib = "792786c7400a136282c1664665ae0a8db921c6c2"
SRC_URI += "git://github.com/pmezard/go-difflib;name=go-difflib;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/pmezard/go-difflib"

# [github.com/klauspost/cpuid/v2 v2.2.7] git ls-remote https://github.com/klauspost/cpuid 486f6ae65fec6bbb15e6f6bff15036f7bc50d4c4
SRCREV_cpuid-v2 = "486f6ae65fec6bbb15e6f6bff15036f7bc50d4c4"
SRC_URI += "git://github.com/klauspost/cpuid;name=cpuid-v2;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/klauspost/cpuid/v2"

# [github.com/modern-go/reflect2 v1.0.2] git ls-remote https://github.com/modern-go/reflect2 2b33151c9bbc5231aea69b8861c540102b087070
SRCREV_reflect2 = "2b33151c9bbc5231aea69b8861c540102b087070"
SRC_URI += "git://github.com/modern-go/reflect2;name=reflect2;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/modern-go/reflect2"

# [github.com/nlpodyssey/gopickle v0.3.0] git ls-remote https://github.com/nlpodyssey/gopickle 15e0f179cabbce73a594e528685627f1fb77bd99
SRCREV_gopickle = "15e0f179cabbce73a594e528685627f1fb77bd99"
SRC_URI += "git://github.com/nlpodyssey/gopickle;name=gopickle;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/nlpodyssey/gopickle"

# [github.com/agnivade/levenshtein v1.1.1] git ls-remote https://github.com/agnivade/levenshtein 51ec67d01101f5fe22e83980dc53e1d5fc96603c
SRCREV_levenshtein = "51ec67d01101f5fe22e83980dc53e1d5fc96603c"
SRC_URI += "git://github.com/agnivade/levenshtein;name=levenshtein;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/agnivade/levenshtein"

# [github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd] git ls-remote https://github.com/modern-go/concurrent bacd9c7ef1dd9b15be4a9909b8ac7a4e313eec94
SRCREV_concurrent = "bacd9c7ef1dd9b15be4a9909b8ac7a4e313eec94"
SRC_URI += "git://github.com/modern-go/concurrent;name=concurrent;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/modern-go/concurrent"

# [github.com/pelletier/go-toml/v2 v2.2.2] git ls-remote https://github.com/pelletier/go-toml a3d5a0bb530b5206c728eed9cb57323061922bcb
SRCREV_go-toml-v2 = "a3d5a0bb530b5206c728eed9cb57323061922bcb"
SRC_URI += "git://github.com/pelletier/go-toml;name=go-toml-v2;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/pelletier/go-toml/v2"

# [github.com/wk8/go-ordered-map/v2 v2.1.8] git ls-remote https://github.com/wk8/go-ordered-map 85ca4a2b29d3241fa4513f82be3d38fe2392a791
SRCREV_go-ordered-map-v2 = "85ca4a2b29d3241fa4513f82be3d38fe2392a791"
SRC_URI += "git://github.com/wk8/go-ordered-map;name=go-ordered-map-v2;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/wk8/go-ordered-map/v2"

# [github.com/apache/arrow/go/arrow v0.0.0-20211112161151-bc219186db40] git ls-remote https://github.com/apache/arrow bc219186db40ec6966eab91ee2dec24b2ebcfca1
SRCREV_arrow = "bc219186db40ec6966eab91ee2dec24b2ebcfca1"
SRC_URI += "git://github.com/apache/arrow;name=arrow;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/apache/arrow/go/arrow"

# [github.com/bahlo/generic-list-go v0.2.0] git ls-remote https://github.com/bahlo/generic-list-go 89fb9b4cdfd4b5295651f72e9f892f1595b4d6c9
SRCREV_generic-list-go = "89fb9b4cdfd4b5295651f72e9f892f1595b4d6c9"
SRC_URI += "git://github.com/bahlo/generic-list-go;name=generic-list-go;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/bahlo/generic-list-go"

# [github.com/tkrajina/go-reflector v0.5.5] git ls-remote https://github.com/tkrajina/go-reflector 27b6085145423eed7ae84e94ee3ab29c289de651
SRCREV_go-reflector = "27b6085145423eed7ae84e94ee3ab29c289de651"
SRC_URI += "git://github.com/tkrajina/go-reflector;name=go-reflector;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/tkrajina/go-reflector"

# [github.com/go-playground/locales v0.14.1] git ls-remote https://github.com/go-playground/locales ce315c8672599942003599943a1e64288f55b03f
SRCREV_locales = "ce315c8672599942003599943a1e64288f55b03f"
SRC_URI += "git://github.com/go-playground/locales;name=locales;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/go-playground/locales"

# [github.com/olekukonko/tablewriter v0.0.5] git ls-remote https://github.com/olekukonko/tablewriter c7d2a8a09b076b70918308a3cd95464b2ae3b5d8
SRCREV_tablewriter = "c7d2a8a09b076b70918308a3cd95464b2ae3b5d8"
SRC_URI += "git://github.com/olekukonko/tablewriter;name=tablewriter;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/olekukonko/tablewriter"

# [github.com/bytedance/sonic/loader v0.1.1] git ls-remote https://github.com/bytedance/sonic 51ea135322cab599c287fe6418df4c2e3c32b65e
SRCREV_loader = "51ea135322cab599c287fe6418df4c2e3c32b65e"
SRC_URI += "git://github.com/bytedance/sonic;name=loader;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/bytedance/sonic/loader"

# [go4.org/unsafe/assume-no-moving-gc v0.0.0-20231121144256-b99613f794b6] git ls-remote https://github.com/go4org/unsafe-assume-no-moving-gc b99613f794b6b2f6d80da53bb131c5c98ea2fdd2
SRCREV_assume-no-moving-gc = "b99613f794b6b2f6d80da53bb131c5c98ea2fdd2"
SRC_URI += "git://github.com/go4org/unsafe-assume-no-moving-gc;name=assume-no-moving-gc;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/go4.org/unsafe/assume-no-moving-gc"

# [github.com/gabriel-vasile/mimetype v1.4.3] git ls-remote https://github.com/gabriel-vasile/mimetype e64d6bdb3607578757d31380818651a9fc95ca8b
SRCREV_mimetype = "e64d6bdb3607578757d31380818651a9fc95ca8b"
SRC_URI += "git://github.com/gabriel-vasile/mimetype;name=mimetype;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/gabriel-vasile/mimetype"

# [github.com/inconshreveable/mousetrap v1.1.0] git ls-remote https://github.com/inconshreveable/mousetrap 4e8053ee7ef85a6bd26368364a6d27f1641c1d21
SRCREV_mousetrap = "4e8053ee7ef85a6bd26368364a6d27f1641c1d21"
SRC_URI += "git://github.com/inconshreveable/mousetrap;name=mousetrap;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/inconshreveable/mousetrap"

# [github.com/twitchyliquid64/golang-asm v0.15.1] git ls-remote https://github.com/twitchyliquid64/golang-asm 8d7f1f783b11f9a00f5bcdfcae17f5ac8f22512e
SRCREV_golang-asm = "8d7f1f783b11f9a00f5bcdfcae17f5ac8f22512e"
SRC_URI += "git://github.com/twitchyliquid64/golang-asm;name=golang-asm;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/twitchyliquid64/golang-asm"

# [github.com/go-playground/validator/v10 v10.20.0] git ls-remote https://github.com/go-playground/validator e20b94842ab102ba94e73eaf66f5c0466e405882
SRCREV_v10 = "e20b94842ab102ba94e73eaf66f5c0466e405882"
SRC_URI += "git://github.com/go-playground/validator;name=v10;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/go-playground/validator/v10"

# [github.com/go-playground/universal-translator v0.18.1] git ls-remote https://github.com/go-playground/universal-translator f83cd526536e253181a13835b00cd107f627c505
SRCREV_universal-translator = "f83cd526536e253181a13835b00cd107f627c505"
SRC_URI += "git://github.com/go-playground/universal-translator;name=universal-translator;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/go-playground/universal-translator"

# [github.com/tkrajina/typescriptify-golang-structs v0.2.0] git ls-remote https://github.com/tkrajina/typescriptify-golang-structs 0a75b3461d57022aac17fc0cae7cdd17993b2754
SRCREV_typescriptify-golang-structs = "0a75b3461d57022aac17fc0cae7cdd17993b2754"
SRC_URI += "git://github.com/tkrajina/typescriptify-golang-structs;name=typescriptify-golang-structs;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/tkrajina/typescriptify-golang-structs"

